version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: bananzza
      POSTGRES_PASSWORD: bananzza_monitor
      POSTGRES_DB: wbmonitoring
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wbuser -d wbmonitoring"]
      interval: 10s
      timeout: 5s
      retries: 5

  wb-monitoring:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - WB_API_KEY=eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjUwMjE3djEiLCJ0eXAiOiJKV1QifQ.eyJlbnQiOjEsImV4cCI6MTc1NjQzNDY5NiwiaWQiOiIwMTk1NDdkMS1mMjQwLTdjYWItOWE0MS03NzYyZjk2NTExYzkiLCJpaWQiOjUzNjU3NjI4LCJvaWQiOjEwODA1MTYsInMiOjc5MzQsInNpZCI6IjdhZDQzMTNjLTMzMjItNDkyNi05YTE2LTUxMTc5MmE0MjE1ZSIsInQiOmZhbHNlLCJ1aWQiOjUzNjU3NjI4fQ.Fao2iueUE2bTK0kpaJu6WOE6hFm3L3iEll8MhsYvWLCXD0LKOr44zf8F5x4Daq_RAQcb7ImTNSstIxubws_kug
      - TELEGRAM_TOKEN=7536169840:AAH_DD6rmuoe3nN3s5t5islOi6tOvjJRZ78
      - TELEGRAM_CHAT_ID=447590340
      - PG_CONN_STRING=postgres://bananzza:bananzza_monitor@db:5432/wbmonitoring?sslmode=disable
      - MONITORING_INTERVAL_MIN=5
      - PRODUCT_UPDATE_INTERVAL_HOUR=5
      - PRICE_THRESHOLD=30
      - STOCK_THRESHOLD=50
      - WORKER_COUNT=5
      - MAX_RETRIES=3
      - RETRY_INTERVAL_SEC=5
      - REQUEST_TIMEOUT_SEC=100

volumes:
  postgres-data:
