version: '3.8'
services:
  # База данных для первого приложения
  db-first:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: bananzza
      POSTGRES_PASSWORD: bananzza_monitor
      POSTGRES_DB: db_first
    volumes:
      - postgres-first:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bananzza -d db_first"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Первое приложение с индивидуальными переменными окружения
  wb-monitoring-first:
    build: .
    restart: always
    depends_on:
      db-first:
        condition: service_healthy
    environment:
      - WB_API_KEY=
      - TELEGRAM_TOKEN=
      - TELEGRAM_CHAT_ID=
      - PG_CONN_STRING=
      - MONITORING_INTERVAL_MIN=10
      - PRODUCT_UPDATE_INTERVAL_HOUR=12
      - PRICE_THRESHOLD=10
      - STOCK_THRESHOLD=100
      - WORKER_COUNT=5
      - MAX_RETRIES=3
      - RETRY_INTERVAL_SEC=5
      - REQUEST_TIMEOUT_SEC=100
      - TELEGRAM_ALLOWED_USER_IDS=
      - SMTP_HOST=mailhog  # Имя сервиса MailHog в Docker Compose сети
      - SMTP_PORT=1025     # Стандартный SMTP порт MailHog
      - SMTP_USER=""       # MailHog не требует авторизации
      - SMTP_PASSWORD=""   # MailHog не требует авторизации
      - SMTP_SSL=false
      - USE_IMPROVED_SERVICES=true

  # База данных для второго приложения
  db-second:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: lasciva
      POSTGRES_PASSWORD: lasciva
      POSTGRES_DB: db_second
    volumes:
      - postgres-second:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lasciva -d db_second"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Второе приложение со своими переменными окружения
  wb-monitoring-second:
    build: .
    restart: always
    depends_on:
      db-second:
        condition: service_healthy
    environment:
      - WB_API_KEY=
      - TELEGRAM_TOKEN=
      - TELEGRAM_CHAT_ID=
      - PG_CONN_STRING=
      - MONITORING_INTERVAL_MIN=10
      - PRODUCT_UPDATE_INTERVAL_HOUR=5
      - PRICE_THRESHOLD=10
      - STOCK_THRESHOLD=100
      - WORKER_COUNT=5
      - MAX_RETRIES=3
      - RETRY_INTERVAL_SEC=5
      - REQUEST_TIMEOUT_SEC=100
      - TELEGRAM_ALLOWED_USER_IDS=
      - SMTP_HOST=mailhog  # Имя сервиса MailHog в Docker Compose сети
      - SMTP_PORT=1025     # Стандартный SMTP порт MailHog
      - SMTP_USER=""       # MailHog не требует авторизации
      - SMTP_PASSWORD=""   # MailHog не требует авторизации
      - SMTP_SSL=false
      - USE_IMPROVED_SERVICES=true

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP порт
      - "8025:8025" # Web UI порт
    container_name: mailhog # Опционально, для удобства
volumes:
  postgres-first:
  postgres-second:
